import '../models/property_model.dart';
import 'mock_agents.dart';

class MockProperties {
  MockProperties._();

  static String _u(String id) => 'https://images.unsplash.com/$id?auto=format&fit=crop&w=1200&q=80';

  static final List<PropertyModel> all = [
    PropertyModel(
      id: 'p1',
      title: 'Modern Skyline Villa',
      images: [
        _u('photo-1613490493576-7fde63acd811'),
        _u('photo-1600585154340-be6161a56a0c'),
        _u('photo-1600607687939-ce8a6c25118c'),
        _u('photo-1600607687644-aac4c3eac7f4'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.villa,
      price: 1250000,
      location: 'Palm Jumeirah',
      city: 'Dubai',
      bedrooms: 5,
      bathrooms: 6,
      areaSqft: 6200,
      rating: 4.9,
      agent: MockAgents.sofia,
      description:
          'An extraordinary waterfront villa offering panoramic skyline views, floor-to-ceiling windows, and a private infinity pool. Thoughtfully designed with an open-concept layout, premium Italian finishes, and smart home automation throughout.',
      amenities: ['Parking', 'Swimming Pool', 'Security', 'Garden', 'Gym', 'Balcony'],
      status: PropertyStatus.active,
      floor: 'Ground + 2',
      furnished: 'Fully Furnished',
      propertyAge: '1 year',
      views: 1240,
      interested: 32,
      postedDate: DateTime(2026, 8, 20),
      featured: true,
      lat: 25.1124,
      lng: 55.139,
    ),
    PropertyModel(
      id: 'p2',
      title: 'Downtown Loft Apartment',
      images: [
        _u('photo-1502672260266-1c1ef2d93688'),
        _u('photo-1493809842364-78817add7ffb'),
        _u('photo-1615873968403-89e068629265'),
      ],
      kind: ListingKind.rent,
      type: PropertyType.apartment,
      price: 3200,
      location: 'Downtown, Business Bay',
      city: 'Dubai',
      bedrooms: 2,
      bathrooms: 2,
      areaSqft: 1150,
      rating: 4.7,
      agent: MockAgents.daniel,
      description:
          'A stylish loft apartment in the heart of downtown, walking distance to shops, cafes and metro. Features an open kitchen, floor-to-ceiling windows, and access to a rooftop lounge.',
      amenities: ['Parking', 'Gym', 'Lift', 'Security', 'Balcony'],
      status: PropertyStatus.active,
      floor: '18th Floor',
      furnished: 'Semi-Furnished',
      propertyAge: '3 years',
      views: 860,
      interested: 21,
      postedDate: DateTime(2026, 8, 28),
      featured: true,
      lat: 25.1868,
      lng: 55.2631,
    ),
    PropertyModel(
      id: 'p3',
      title: 'Cozy Family House',
      images: [
        _u('photo-1568605114967-8130f3a36994'),
        _u('photo-1600566753086-00f18fb6b3ea'),
        _u('photo-1583608205776-bfd35f0d9f83'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.house,
      price: 485000,
      location: 'Arabian Ranches',
      city: 'Dubai',
      bedrooms: 4,
      bathrooms: 3,
      areaSqft: 3100,
      rating: 4.5,
      agent: MockAgents.amara,
      description:
          'A warm and inviting family home set within a quiet, tree-lined community. Includes a landscaped backyard, double garage, and a bright, functional kitchen perfect for family gatherings.',
      amenities: ['Parking', 'Garden', 'Security', 'Balcony'],
      status: PropertyStatus.active,
      furnished: 'Unfurnished',
      propertyAge: '5 years',
      views: 512,
      interested: 14,
      postedDate: DateTime(2026, 8, 15),
      lat: 25.0515,
      lng: 55.2708,
    ),
    PropertyModel(
      id: 'p4',
      title: 'Seaview Penthouse Suite',
      images: [
        _u('photo-1512917774080-9991f1c4c750'),
        _u('photo-1600607687939-ce8a6c25118c'),
        _u('photo-1571939228382-b2f2b585ce15'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.apartment,
      price: 2100000,
      location: 'Dubai Marina',
      city: 'Dubai',
      bedrooms: 4,
      bathrooms: 5,
      areaSqft: 4200,
      rating: 5.0,
      agent: MockAgents.maria,
      description:
          'An exclusive penthouse perched above the marina skyline, offering uninterrupted sea views, a private terrace with a plunge pool, and bespoke interior finishes throughout.',
      amenities: ['Parking', 'Swimming Pool', 'Gym', 'Security', 'Lift', 'Balcony'],
      status: PropertyStatus.active,
      floor: 'Penthouse',
      furnished: 'Fully Furnished',
      propertyAge: 'New',
      views: 2130,
      interested: 58,
      postedDate: DateTime(2026, 9, 1),
      featured: true,
      lat: 25.0805,
      lng: 55.1403,
    ),
    PropertyModel(
      id: 'p5',
      title: 'Sunny Garden Townhouse',
      images: [
        _u('photo-1580587771525-78b9dba3b914'),
        _u('photo-1600585154340-be6161a56a0c'),
        _u('photo-1523192193543-6e7296d960e4'),
      ],
      kind: ListingKind.rent,
      type: PropertyType.house,
      price: 4800,
      location: 'Jumeirah Village Circle',
      city: 'Dubai',
      bedrooms: 3,
      bathrooms: 3,
      areaSqft: 2200,
      rating: 4.4,
      agent: MockAgents.ethan,
      description:
          'A bright and airy townhouse featuring a private garden, modern kitchen, and dedicated parking for two cars. Located in a family-friendly gated community with a shared pool.',
      amenities: ['Parking', 'Garden', 'Swimming Pool', 'Security'],
      status: PropertyStatus.active,
      furnished: 'Semi-Furnished',
      propertyAge: '2 years',
      views: 340,
      interested: 9,
      postedDate: DateTime(2026, 8, 5),
      lat: 25.0611,
      lng: 55.2126,
    ),
    PropertyModel(
      id: 'p6',
      title: 'Elegant Studio Residence',
      images: [
        _u('photo-1493809842364-78817add7ffb'),
        _u('photo-1615873968403-89e068629265'),
        _u('photo-1505843513577-22bb7d21e455'),
      ],
      kind: ListingKind.rent,
      type: PropertyType.apartment,
      price: 1900,
      location: 'Al Barsha',
      city: 'Dubai',
      bedrooms: 1,
      bathrooms: 1,
      areaSqft: 650,
      rating: 4.2,
      agent: MockAgents.daniel,
      description:
          'A compact, well-designed studio ideal for young professionals. Close to public transport, supermarkets, and dining options, with 24/7 building security.',
      amenities: ['Lift', 'Security', 'Parking'],
      status: PropertyStatus.pending,
      floor: '4th Floor',
      furnished: 'Fully Furnished',
      propertyAge: '4 years',
      views: 198,
      interested: 5,
      postedDate: DateTime(2026, 8, 30),
      lat: 25.1122,
      lng: 55.2003,
    ),
    PropertyModel(
      id: 'p7',
      title: 'Riverside Executive Villa',
      images: [
        _u('photo-1523480717984-091a04b31067'),
        _u('photo-1613977257363-707ba9348227'),
        _u('photo-1600607687644-aac4c3eac7f4'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.villa,
      price: 1780000,
      location: 'Emirates Hills',
      city: 'Dubai',
      bedrooms: 6,
      bathrooms: 7,
      areaSqft: 8100,
      rating: 4.9,
      agent: MockAgents.sofia,
      description:
          'A grand executive villa overlooking the golf course, featuring a private cinema, home office, staff quarters, and a resort-style backyard with an infinity pool.',
      amenities: ['Parking', 'Swimming Pool', 'Gym', 'Security', 'Garden', 'Generator'],
      status: PropertyStatus.active,
      furnished: 'Unfurnished',
      propertyAge: '3 years',
      views: 980,
      interested: 27,
      postedDate: DateTime(2026, 7, 22),
      featured: true,
      lat: 25.058,
      lng: 55.169,
    ),
    PropertyModel(
      id: 'p8',
      title: 'Contemporary City Office',
      images: [
        _u('photo-1523217582562-09d0def993a6'),
        _u('photo-1519642918688-7e43b19245d8'),
      ],
      kind: ListingKind.rent,
      type: PropertyType.office,
      price: 6200,
      location: 'Sheikh Zayed Road',
      city: 'Dubai',
      bedrooms: 0,
      bathrooms: 2,
      areaSqft: 2600,
      rating: 4.3,
      agent: MockAgents.ethan,
      description:
          'A fully fitted office space in a prime business tower with reception area, meeting rooms, and access to shared conference facilities. Ideal for growing teams.',
      amenities: ['Parking', 'Lift', 'Security', 'Generator'],
      status: PropertyStatus.active,
      floor: '22nd Floor',
      furnished: 'Fully Furnished',
      propertyAge: '6 years',
      views: 275,
      interested: 8,
      postedDate: DateTime(2026, 8, 12),
      lat: 25.2138,
      lng: 55.2794,
    ),
    PropertyModel(
      id: 'p9',
      title: 'Beachfront Apartment',
      images: [
        _u('photo-1484154218962-a197022b5858'),
        _u('photo-1600607687939-ce8a6c25118c'),
        _u('photo-1571939228382-b2f2b585ce15'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.apartment,
      price: 950000,
      location: 'Jumeirah Beach Residence',
      city: 'Dubai',
      bedrooms: 3,
      bathrooms: 3,
      areaSqft: 1850,
      rating: 4.8,
      agent: MockAgents.maria,
      description:
          'Wake up to ocean views in this beautifully finished beachfront apartment. Steps away from the beach walk, restaurants, and boutique shopping.',
      amenities: ['Parking', 'Swimming Pool', 'Gym', 'Balcony', 'Security'],
      status: PropertyStatus.active,
      floor: '9th Floor',
      furnished: 'Fully Furnished',
      propertyAge: '2 years',
      views: 1420,
      interested: 44,
      postedDate: DateTime(2026, 8, 18),
      featured: true,
      lat: 25.0787,
      lng: 55.1339,
    ),
    PropertyModel(
      id: 'p10',
      title: 'Vacant Residential Plot',
      images: [
        _u('photo-1500382017468-9049fed747ef'),
        _u('photo-1500382017468-9049fed747ef'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.land,
      price: 620000,
      location: 'Al Furjan',
      city: 'Dubai',
      bedrooms: 0,
      bathrooms: 0,
      areaSqft: 5000,
      rating: 4.0,
      agent: MockAgents.amara,
      description:
          'A clear, ready-to-build residential plot in a rapidly developing neighborhood, close to schools and main highways. G+2 permitted.',
      amenities: ['Security'],
      status: PropertyStatus.draft,
      propertyAge: 'N/A',
      views: 76,
      interested: 3,
      postedDate: DateTime(2026, 9, 2),
      lat: 25.0169,
      lng: 55.1425,
    ),
    PropertyModel(
      id: 'p11',
      title: 'Retail Shop – Mall Frontage',
      images: [
        _u('photo-1441986300917-64674bd600d8'),
        _u('photo-1441986300917-64674bd600d8'),
      ],
      kind: ListingKind.rent,
      type: PropertyType.shop,
      price: 8500,
      location: 'Al Wasl Road',
      city: 'Dubai',
      bedrooms: 0,
      bathrooms: 1,
      areaSqft: 900,
      rating: 4.1,
      agent: MockAgents.ethan,
      description:
          'High-visibility retail unit with excellent foot traffic on Al Wasl Road. Suitable for boutique retail, salon, or cafe use.',
      amenities: ['Parking', 'Security', 'Generator'],
      status: PropertyStatus.active,
      furnished: 'Unfurnished',
      propertyAge: '4 years',
      views: 152,
      interested: 6,
      postedDate: DateTime(2026, 8, 9),
      lat: 25.1937,
      lng: 55.2517,
    ),
    PropertyModel(
      id: 'p12',
      title: 'Skyline Corner Villa',
      images: [
        _u('photo-1554995207-c18c203602cb'),
        _u('photo-1600585154340-be6161a56a0c'),
      ],
      kind: ListingKind.sale,
      type: PropertyType.villa,
      price: 1395000,
      location: 'Dubai Hills Estate',
      city: 'Dubai',
      bedrooms: 5,
      bathrooms: 5,
      areaSqft: 5400,
      rating: 4.7,
      agent: MockAgents.sofia,
      description:
          'A recently sold corner villa with a spacious layout, private pool, and landscaped garden — a great benchmark for similar homes in the community.',
      amenities: ['Parking', 'Swimming Pool', 'Garden', 'Security', 'Gym'],
      status: PropertyStatus.sold,
      furnished: 'Semi-Furnished',
      propertyAge: '2 years',
      views: 1890,
      interested: 61,
      postedDate: DateTime(2026, 6, 14),
      lat: 25.107,
      lng: 55.243,
    ),
  ];

  static PropertyModel byId(String id) => all.firstWhere((p) => p.id == id, orElse: () => all.first);

  static List<PropertyModel> get featured => all.where((p) => p.featured).toList();
  static List<PropertyModel> get recommended => all.take(6).toList();
  static List<PropertyModel> get nearby => (all.toList()..shuffle()).take(5).toList();
  static List<PropertyModel> get recentlyAdded =>
      (all.toList()..sort((a, b) => (b.postedDate ?? DateTime(2000)).compareTo(a.postedDate ?? DateTime(2000))));

  static List<PropertyModel> byAgent(String agentId) => all.where((p) => p.agent.id == agentId).toList();

  static List<PropertyModel> byStatus(PropertyStatus status) =>
      all.where((p) => p.status == status).toList();

  static const List<String> popularLocations = [
    'Dubai Marina',
    'Downtown Dubai',
    'Palm Jumeirah',
    'Arabian Ranches',
    'Business Bay',
    'JVC',
  ];
}
